export const DEFAULT_CATEGORIES = [
  "Video",
  "Audio",
  "Image",
  "Animation",
  "3D",
  "Writing",
  "Data Analysis",
  "Social Media",
  "Productivity",
  "Development",
  "Design",
  "Chatbot",
  "Daily Life",
  "Legal",
  "Finance",
  "Marketing",
  "Health",
  "Research",
  "Education",
  "Translation",
  "Management",
  "Inspiration",
];

export const DEFAULT_TAGS = [
  "AI",
  "Automation",
  "Productivity",
  "Design",
  "Marketing",
  "Analytics",
  "Research",
  "Beginner",
  "Browser Extension",
  "Mobile",
  "Free",
  "Paid",
  "Creative Suite",
  "Management",
  "Security",
  "Workflow",
  "Branding",
  "Inspiration",
  "No Code",
  "Operations",
];
